version: 0.1.0                                            

name: Deploy a NextJS website to GitHub Pages  
description: A GitHub Stack to develop, preview, and deploy a NextJS website to Github Pages in seconds.

branding:                                                # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                                  # stack inputs 
  - name: NODE_VERSION                                   # stack input name
    default: v12.22.4                                    # stack input default value provided
    description: Node.js version.                        # stack input description
    validvalues:                                         # stack input valid values that can be selected
    - v12.22.4
    - v14.17.4

configs:
  repo-metadata:
    parameters:
      description: 'NextJS app on GitHub pages'
      topics:
      - nextjs
      - github-pages

  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
  uses: "stack-init.yaml"
